<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240922200323 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE event_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, type VARCHAR(255) NOT NULL, broker VARCHAR(255) NOT NULL, payload TEXT NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX event_log__user_id__broker__uniq ON event_log (user_id, broker)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE event_log');
    }
}
