{
 "title": "RabbitMQ vs Kafka",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total messages consumed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "target": "movingSum(stats_counts.app.kafka.processed.total, '1hour')"
    },
    {
     "target": "movingSum(stats_counts.app.rabbit_mq.processed.total, '1hour')"
    }
   ]
  },
  {
   "title": "Messages per period",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "stats_counts.app.kafka.processed.total"
    },
    {
     "target": "stats_counts.app.rabbit_mq.processed.total"
    }
   ]
  },
  {
   "title": "Messages per consumer for the period",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "movingSum(stats_counts.app.kafka.processed.consumer_0, '2min')"
    },
    {
     "target": "movingSum(stats_counts.app.rabbit_mq.processed.consumer_0, '2min')"
    },
    {
     "target": "movingSum(stats_counts.app.kafka.processed.consumer_1, '2min')"
    },
    {
     "target": "movingSum(stats_counts.app.rabbit_mq.processed.consumer_1, '2min')"
    },
    {
     "target": "movingSum(stats_counts.app.kafka.processed.consumer_2, '2min')"
    },
    {
     "target": "movingSum(stats_counts.app.kafka.processed.consumer_3, '2min')"
    },
    {
     "target": "movingSum(stats_counts.app.rabbit_mq.processed.consumer_2, '2min')"
    },
    {
     "target": "movingSum(stats_counts.app.rabbit_mq.processed.consumer_3, '2min')"
    }
   ]
  },
  {
   "title": "Number of collisions because of race condition",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "stats_counts.app.kafka.race_condition"
    },
    {
     "target": "stats_counts.app.rabbit_mq.race_condition"
    }
   ]
  },
  {
   "title": "Number of violations of processing order",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "target": "stats_counts.app.kafka.broken_order"
    },
    {
     "target": "stats_counts.app.rabbit_mq.broken_order"
    }
   ]
  }
 ]
}